# Generated by Django 5.2.7 on 2025-10-07 00:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicion',
            name='dispositivo',
        ),
        migrations.RenameField(
            model_name='dispositivo',
            old_name='creado_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='consumo',
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='limite_consumo',
        ),
        migrations.RemoveField(
            model_name='zona',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='categoria',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoria',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10),
        ),
        migrations.AddField(
            model_name='categoria',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='consumo_maximo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='zona',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zona',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zona',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10),
        ),
        migrations.AddField(
            model_name='zona',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dispositivos.categoria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='zona',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dispositivos.zona'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Alerta',
        ),
        migrations.DeleteModel(
            name='Medicion',
        ),
    ]
